### ISSUE TITLE
Exposing Optional Argument for Build Version

### ISSUE THREAD

**Issue by joshj76** [jovianarts/LVSolutionBuilder#49]
I have a use case where I am calling the Solution Builder via the command line, and I would like to have the ability to specify the build version of the object(s) that I am building. This would provide me with more control over the versioning instead of relying solely on the "Auto-increment version on build" functionality of each build spec. This would also allow for incrementing the major/minor/patch versions in addition to the build version without having to manually update each build spec.  

This may also make sense to expose in the Solution File use case (if that handling is different).

**Comment by jovianarts** [comment]
Thanks for the request @joshj76, let's chat about it for moment. To give you a little background, I've felt that a couple of points were important to this project:
1. Avoid modifying the project file on disk and instead perform actions on the project in memory.
2. Don't rewrite the LV AppBuilder, instead project specifications are the main source of truth.

The reason for bullet 1 was that a lot of us use source code control and our pipelines generally don't resubmit changed files back into SCC after the build completes, but a record of the project file used matters for repeatability. And the main reason for bullet 2 is that I could see that quickly see that escalate, followed by requests like "I'd like to be able to overwrite the build output location", "turn on/off certain build flag like Enable Debugging", etc. 

I've tried really hard to not break those points. The closest I've come was to support building multiple targets in 1 project, but I feel that the splitting a project into separate files (that then get cleaned up) didn't break bullet 1 since the split is an exact subset copy of the original.

Regarding your request, I feel that it starts to break bullet 2 and is more an act of convenience rather than a fix to a blocking issue. Instead, I would recommend a workflow that disables auto-incrementing of versions in your project file, and have a separate part of your build process that sets the version you want to use before calling Solution Builder.

Circling back, I did want to let you know that before drafting this reply, I did put thought into how to go about accomplishing this and there were a further hurdles to consider: What is the level of granularity the version should be applied to. PPLs only? Solution Builder supports building all build types so would the new version apply to all the build specification in a single project? How would you expose setting different versions for different build specs in the same project? There are likely a few more use-cases that would need to be solved, but this is where having you do that separately affords you the flexibility to only update the specs you want.

The last use case that got me thinking is that if specifying a version means that you want all binaries to have matching versions, you should include the `-Rebuild` flag when invoking Solution Builder to ensure that incremental builds are ignored and forces a rebuild of all the binaries.

I'd love to hear your thoughts on this!

**Comment by jovianarts** [comment]
Hey @joshj76 , I recently had a great chat with @KarthikAbiram about this request and I'm beginning to change my mind about some my previous comments. I now have more thoughts on how to implement this functionality in a way that still aligns with the project directives, and I'm going to take a little time to think about moving forward with it.

**Comment by joshj76** [comment]
@jovianarts , my apologies for neglecting to provide you with a response last week.  

With regard to the previous comments you made above, you provided a lot of good thoughts that made me feel I presented a potential solution to the problem I am facing instead of stating the problem. My user story could be summarized as follows:  

**"As a developer who uses an automated build process, I want to have my CI pipeline automatically determine the build number for new builds to prevent user-error in setting the correct Major, Minor, and Patch version numbers."**  

My vision for how to achieve this included using the LV Solution Builder to define what is being built in the pipeline, as all the needed information is fully contained within the LV Solution Builder file. Consequentially, having an additional step to examine the LV Solution Builder configuration to determine which projects are being included and then modifying the required build specs to set the version number before sending the info back to the Solution Builder feels like excessive overhead.  **That said, am I envisioning your suggestion correctly, or were you suggesting something different?**  

As for your questions on granularity and how to expose setting different versions for different build specs, a motivating influence for my request was the MGI Solution Explorer which sets the same version number for all items in the solution. I think this would probably be the easiest path forward and would be an appropriate solution. I don't have a great solution off hand if we want more granular builds, though.  

Again, my apologies for having such a delayed response, but thank you for your thoughts and input thus far.

**Comment by jovianarts** [comment]
Hi @joshj76 and , PR #51 adds support for version. Feel free to read the PR description and updated documentation for usage.
